### ISSUE TITLE
Abandonned project?

### ISSUE THREAD

**Issue by patcon** [igal/pocketknife#5]
Just wondering. Is this abandonned? If so, could you explain whether it's a lack of time, a lack of interest, or perhaps a better alternative that's out there (I'm aware of soloist and some cap-chef combinations, but none seem as organized as this).

I only ask because there are a few pull requests that seem to have some good code, and yet there's no communication from the maintainer in the threads.

Thanks anyhow though. I don't mean to seem ungrateful for the great codebase to work with -- just wondering what I'm getting into if I fork :)

**Comment by igal** [comment]
Thanks for the encouragement and reminder. 

I'm sorry for appearing unresponsive, the pull request and issues were created against the project during a very busy time for me and I forgot about them, and haven't had any reason to go visit the github page for the project since to notice that there was activity on the issues and pull requests. Sigh.

I've made a new 0.2.0 release with a number of new features and fixes.
